version: '3.8'
services:
  # Other services like your app, etc.
  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:Abc%4012345@66.42.43.15:5433/Comics?schema=account"
    networks:
      - hostnet

networks:
  hostnet:
    external: true
    name: host
