version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc@12345
      POSTGRES_DB: Comics
    networks:
      - hostnet

networks:
  hostnet:
    external: true
    name: host
